config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validate :validate_detail

  private

  def validate_detail
    schema = load_json_schema
    JSON::Validator.fully_validate(schema, detail, errors_as_objects: true)
  end

  def load_json_schema
    case category
    when 'book_shop' then
      JSON.dump(YAML.load(File.open('./config/json_schema/book_shop.yml').read))
    else
      JSON.dump(YAML.load(File.open('./config/json_schema/default.yml').read))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_item_details, only: [:edit]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_save_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_save_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def item_save_params
      {
        title: item_params[:title],
        category: item_params[:category],
        detail: detail_json
      }
    end

    def detail_json
      {
        tags: [
          item_params[:detail_tags_1],
          item_params[:detail_tags_2],
          item_params[:detail_tags_3]
        ]
      }.to_json
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.permit(
        :title,
        :category,
        :detail_tags_1,
        :detail_tags_2,
        :detail_tags_3
      )
    end

    def set_item_details
      detail = JSON.parse(@item.detail).symbolize_keys
      tags = detail[:tags] || []
      @detail_tags_1 = tags[0]
      @detail_tags_2 = tags[1]
      @detail_tags_3 = tags[2]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_field :detail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= form_tag("/items/#{@item.id}", method: 'patch') do %>
  <div>
    <%= label_tag(:title, "title") %>
    <%= text_field_tag(:title, @item.title) %>
  </div>
  <div>
    <%= label_tag(:category, "category") %>
    <%= text_field_tag(:category, @item.category) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_1, "detail_tags_1") %>
    <%= text_field_tag(:detail_tags_1, @detail_tags_1) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_2, "detail_tags_2") %>
    <%= text_field_tag(:detail_tags_2, @detail_tags_2) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_3, "detail_tags_3") %>
    <%= text_field_tag(:detail_tags_3, @detail_tags_3) %>
  </div>
  <%= submit_tag('更新') %>
<% end %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.category %></td>
        <td><%= item.detail %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_tag("/items") do %>
  <div>
    <%= label_tag(:title, "title") %>
    <%= text_field_tag(:title, @item.title) %>
  </div>
  <div>
    <%= label_tag(:category, "category") %>
    <%= text_field_tag(:category, @item.category) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_1, "detail_tags_1") %>
    <%= text_field_tag(:detail_tags_1, @detail_tags_1) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_2, "detail_tags_2") %>
    <%= text_field_tag(:detail_tags_2, @detail_tags_2) %>
  </div>
  <div>
    <%= label_tag(:detail_tags_3, "detail_tags_3") %>
    <%= text_field_tag(:detail_tags_3, @detail_tags_3) %>
  </div>
  <%= submit_tag('登録') %>
<% end %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @item.detail %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJson</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>